### ISSUE TITLE
Mac OS 

### ISSUE THREAD

**Issue by jithinraj** [ekivolowitz/notion-cli#3]
It would be nice to have the Mac OS installation guide in Read me, let me know how I can be of any help.

Awesome work, Evan. A much-needed feature for Notion.

**Comment by ekivolowitz** [comment]
To install on Mac, just install [python3](https://docs.python-guide.org/starting/install3/osx/) and then `pip install notion-py`, and the rest of the instructions are the same as in the readme. 

Right now everything is pretty barebones, but I'll be prettying everything up as time goes on.
